In [4]:
import numpy as np

#Manual defintion of "random" data matrix

#data = np.array([[1, 5, 3, 7],[-2, 5, 2, -6],[5, 8, 11, 0]])
data= np.random.rand(3,4)
print(data)

[[0.37412853 0.45120483 0.64097275 0.70451103]
 [0.53099163 0.55707882 0.30860676 0.6861745 ]
 [0.02504089 0.98004249 0.74045536 0.01810972]]


In [5]:
#calculate row and column averages
row_mean = np.mean(data, axis = 0)
print('Mean of rows (along, column,  axis 0) is ', row_mean)

col_mean = np.mean(data, axis = 1)
print('Mean of columns (along row,  axis 1) is ', col_mean)

full_mean = np.mean(data)

print('Mean of all the elements in data is ', full_mean)

Mean of rows (along, column,  axis 0) is  [0.31005368 0.66277538 0.56334496 0.46959842]
Mean of columns (along row,  axis 1) is  [0.54270428 0.52071293 0.44091212]
Mean of all the elements in data is  0.5014431097492519


In [7]:
data[2,2] =100
print(data)

[[3.74128528e-01 4.51204826e-01 6.40972752e-01 7.04511034e-01]
 [5.30991628e-01 5.57078824e-01 3.08606762e-01 6.86174496e-01]
 [2.50408919e-02 9.80042493e-01 1.00000000e+02 1.81097239e-02]]


In [ ]:
#Print out one row of data matrix:
print(data[0,:])

In [ ]:
#Print out rows of data one-by-one

for i in range(data.shape[0]):
    print(data[i,:])

In [8]:
#print out every element of matrix one-by-one
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        print(data[i,j])

0.37412852801669316
0.4512048257282816
0.6409727518028192
0.7045110343288947
0.5309916282030258
0.5570788242830371
0.3086067620874573
0.6861744964331467
0.025040891945259713
0.9800424933753957
100.0
0.018109723932105082
