In [1]:
import numpy as np

In [3]:
a = np.random.rand(3,4)

In [10]:
a.shape

(3, 4)

In [16]:
np.mean(a)

0.5008425520043532

In [17]:
a[1,0] = 100
print(a)

[[4.22005801e-02 3.07961917e-01 7.09486017e-01 2.20804212e-01]
 [1.00000000e+02 8.94228967e-01 7.07610118e-01 7.05045370e-01]
 [5.09625045e-01 8.82841496e-01 1.24285747e-02 5.94222695e-01]]


In [26]:
#Use for-loop to read and print every row of matrix (one-by-one)
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i, j])

0.04220058009896388
0.30796191701071185
0.7094860169353063
0.22080421188429522
100.0
0.8942289669223223
0.7076101177745802
0.7050453701610304
0.5096250454523118
0.882841496462801
0.012428574688991612
0.5942226954438337


In [37]:
x = np.random.rand(5,8)
y = np.random.rand(5,8)
print(x)
print("_________________________")
print(y)
print("_________________________")

z = x*y

print(z)

[[0.91226424 0.13805732 0.26210612 0.42401214 0.05049601 0.7628988
  0.93807387 0.8105453 ]
 [0.14044598 0.85277387 0.06621244 0.65327801 0.75378689 0.30234919
  0.32045592 0.97933448]
 [0.0074479  0.84739699 0.4196165  0.95691062 0.44537861 0.19258462
  0.11425163 0.92925605]
 [0.41960105 0.67062866 0.85166272 0.87822663 0.43012556 0.61412803
  0.5410172  0.61004687]
 [0.90398287 0.55274319 0.17135389 0.06794268 0.19547123 0.50413482
  0.9278629  0.7241284 ]]
_________________________
[[0.77005681 0.19755595 0.41106925 0.51419816 0.22461734 0.59104027
  0.33779658 0.33920751]
 [0.99595192 0.24912843 0.28304764 0.3749627  0.19260153 0.21121766
  0.34247835 0.47023283]
 [0.89605344 0.01235994 0.39171339 0.32040746 0.01520421 0.31391624
  0.07786361 0.4410353 ]
 [0.3149047  0.28502616 0.52168772 0.44033082 0.04447633 0.8827895
  0.81475223 0.78209673]
 [0.74515143 0.04267174 0.83689123 0.64886409 0.69862703 0.80423249
  0.49897924 0.78680709]]
_________________________
[[0.70249529 0.027

In [38]:
z *= 10

print(z)

[[7.0249529  0.27274045 1.07743767 2.18026258 0.1134228  4.50903912
  3.16878144 2.74943055]
 [1.39877447 2.12450213 0.18741275 2.44954886 1.4518051  0.63861489
  1.09749214 4.60515227]
 [0.06673715 0.10473778 1.64369401 3.06601298 0.06771632 0.60455439
  0.08896044 4.09834723]
 [1.32134342 1.91146712 4.44301984 3.86710251 0.19130404 5.4214578
  4.40794972 4.77115658]
 [6.73604129 0.23586516 1.43404564 0.44085565 1.36561483 4.05441604
  4.62984327 5.69749358]]
